# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
    ]
