# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topstories',
            old_name='submitted_by',
            new_name='by',
        ),
        migrations.RemoveField(
            model_name='topstories',
            name='story_id',
        ),
    ]
