# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0002_auto_20190103_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topstories',
            name='by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='description',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topstories',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
