# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0003_auto_20190103_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topstories',
            name='description',
        ),
    ]
